/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES, handleImageOptimization } from 'vinext/server/image-optimization';
import handler from 'vinext/server/app-router-entry';

interface Fetcher {
  fetch(input: Request | string, init?: RequestInit): Promise<Response>;
}

interface Env {
  ASSETS: Fetcher;
  NEXT_PUBLIC_SITE_URL?: string;
  NEXT_PUBLIC_API_BASE_URL?: string;
  NEXT_PUBLIC_GA_MEASUREMENT_ID?: string;
  GOOGLE_SITE_VERIFICATION?: string;
  SITE_LAST_MODIFIED?: string;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

function syncProcessEnvFromBindings(env?: Partial<Env>) {
  if (typeof process === 'undefined' || !process.env) return;

  const sourceEnv = env ?? {};

  const bindings: Record<string, string | undefined> = {
    NEXT_PUBLIC_SITE_URL: sourceEnv.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_API_BASE_URL: sourceEnv.NEXT_PUBLIC_API_BASE_URL,
    NEXT_PUBLIC_GA_MEASUREMENT_ID: sourceEnv.NEXT_PUBLIC_GA_MEASUREMENT_ID,
    GOOGLE_SITE_VERIFICATION: sourceEnv.GOOGLE_SITE_VERIFICATION,
    SITE_LAST_MODIFIED: sourceEnv.SITE_LAST_MODIFIED,
  };

  for (const [key, value] of Object.entries(bindings)) {
    if (typeof value === 'string' && value.length > 0) {
      process.env[key] = value;
    }
  }
}

export default {
  async fetch(request: Request, env?: Env, ctx?: ExecutionContext): Promise<Response> {
    syncProcessEnvFromBindings(env);

    const url = new URL(request.url);

    if (url.pathname === '/_vinext/image' && env?.ASSETS && env?.IMAGES) {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(
        request,
        {
          fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body)
              .transform(width > 0 ? { width } : {})
              .output({ format, quality });
            return result.response();
          },
        },
        allowedWidths,
      );
    }

    if (url.pathname === '/favicon.ico' && env?.ASSETS) {
      return env.ASSETS.fetch(new Request(new URL('/favicon.svg', request.url)));
    }

    return handler.fetch(request, env, ctx);
  },
};
